server:
  port: 9001

springdoc:
  swagger-ui:
    operations-sorter: method
    tags-sorter: alpha

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/powerup-smallsquare
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
appDescription: "Pragma Powerup"
appVersion: "1.0.0"

powerup_usermicroservice_url: "http://localhost:9000/api/v1"